---
- name: install elasticsearch
  hosts: masters
  roles:
  - role: openshift_logging_certs
    vars:
      generated_certs_dir: /home/centos/prod-es-certs
      svc_name: prodes
      kubeconfig: /home/centos/.kube/config
      openshift_logging_kibana_hostname: kibana-dh-prod-storage.cloud.upshift.engineering.redhat.com
  - role: openshift_logging_elasticsearch
    vars:
      full_restart_cluster: True
      openshift_image_tag: v3.10
      kubeconfig: /home/centos/.kube/config
      openshift_is_containerized: False
      __es_version: "5.5"
      __base_file_dir: "5.x"
      openshift_logging_es5_techpreview: True
      openshift_logging_image_version: techpreview
      openshift_logging_elasticsearch_proxy_image_prefix: "docker.io/openshift/"
      openshift_logging_elasticsearch_proxy_image_version: "v1.0.0"
      openshift_logging_es_log_appenders: ['file']
      openshift_logging_elasticsearch_namespace: "dh-prod-storage"
      openshift_logging_namespace: dh-prod-storage
      openshift_logging_elasticsearch_clustername: "prodes"
      openshift_logging_elasticsearch_sa_name: "sa-elasticsearch"
      openshift_logging_elasticsearch_clusterreader: false
      generated_certs_dir: /home/centos/prod-es-certs
      openshift_logging_elasticsearch_transport_cert_name: "elasticsearch"
      openshift_logging_elasticsearch_api_cert_name: "logging-es"
      openshift_logging_elasticsearch_prometheus_sa: system:serviceaccount:dh-prod-storage:prometheus
      oc_username: system:serviceaccount:dh-prod-ci:default/
      openshift_logging_elasticsearch_node_topology:
      - node_role:  master
        replicas: 3
        storage_group: 65534
        node_storage_type: emptydir
        limits:
          memory: 2Gi
          cpu: 2
        requests:
          memory: 1Gi
          cpu: 200m
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 16Gi
          cpu: 2
        requests:
          cpu: 1000m
          memory: 4Gi
        hostmount_path:
        - /elasticsearch
        nodeSelector:
          kubernetes.io/hostname: elasticsearch-001.infra.prod.upshift.eng.rdu2.redhat.com
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 16Gi
          cpu: 2
        requests:
          cpu: 1000m
          memory: 4Gi
        hostmount_path:
        - /elasticsearch
        nodeSelector:
          kubernetes.io/hostname: elasticsearch-002.infra.prod.upshift.eng.rdu2.redhat.com
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 16Gi
          cpu: 2
        requests:
          cpu: 1000m
          memory: 4Gi
        hostmount_path:
        - /elasticsearch
        nodeSelector:
          kubernetes.io/hostname: elasticsearch-003.infra.prod.upshift.eng.rdu2.redhat.com

      openshift_logging_elasticsearch_log_appenders: console
      openshift_logging_elasticsearch_node_topology_defined: "true"
      openshift_logging_elasticsearch_allow_external: true
      openshift_logging_image_prefix: docker-registry.engineering.redhat.com/aicoe/
      openshift_logging_image_pull_secret: ''
      openshift_logging_es_hostname: elastic1-dh-prod-storage.cloud.upshift.engineering.redhat.com
      node_quorum: 2
      expected_data_nodes: 3
